export const surpriseMePrompts = [
  "Realistic portrait of a young woman with curly hair, wearing a red jacket, against a cityscape background at sunset.",
"A man with short black hair, wearing glasses, sitting in a modern office with a view of skyscrapers.",
"A close-up shot of a smiling teenage girl with blonde hair, wearing a blue hoodie, with a blurred forest in the background.",
"A boy with brown hair and freckles, playing soccer on a sunny day in a park.",
"A realistic scene of a girl in a white dress, standing in a field of sunflowers at dawn.",
"Portrait of a man with a beard, wearing a leather jacket, against a rugged mountain backdrop.",
"A young woman in a green dress, walking through a misty forest, with rays of light shining through the trees.",
"A close-up of a girl with dark curly hair, wearing a red scarf, with a snowy mountain in the background.",
"A boy with short blonde hair, sitting on a beach at sunset, gazing out at the ocean.",
"A serene landscape with a girl standing at the edge of a cliff overlooking a vast, tranquil lake.",
"A realistic portrait of an older woman with silver hair, smiling gently in a sunlit garden.",
"A young boy wearing a white t-shirt, exploring a dense jungle with exotic plants and wildlife.",
"A woman with short, purple hair, standing in the middle of a bustling city street at night, illuminated by neon lights.",
"A boy with a baseball cap, sitting on a grassy hill, watching the stars under a clear night sky.",
"A girl with long black hair, walking through a golden wheat field during the harvest season.",
"A group of friends, two girls and a boy, laughing together in a vibrant autumn forest.",
"A young man with glasses and a black hoodie, surrounded by tall skyscrapers under a bright blue sky.",
"A scenic mountain landscape with a girl on horseback, riding along a winding trail with snow-capped peaks.",
"A close-up of a boy with curly hair, holding a lantern, walking through a dark enchanted forest.",
"A girl with a ponytail, wearing a yellow raincoat, standing under an umbrella in a rainy city street.",
  ];